# Generated by Django 4.1.3 on 2022-11-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobro_x_día', models.CharField(max_length=20)),
                ('fecha_entrada', models.DateField(max_length=30)),
                ('fecha_salida', models.DateField(max_length=30)),
                ('cant_personas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_x_día', models.CharField(max_length=30)),
                ('costo_gestion', models.CharField(max_length=30)),
                ('costo_mant', models.CharField(max_length=30)),
                ('costo_limpieza', models.CharField(max_length=30)),
                ('ganancia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
            ],
        ),
    ]
