# Generated by Django 4.1.2 on 2022-11-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp1', '0002_remove_depto_cant_personas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ganancia',
            old_name='precio_x_día',
            new_name='precio_x_dia',
        ),
    ]
