# Generated by Django 4.1.3 on 2022-11-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp1', '0003_rename_precio_x_día_ganancia_precio_x_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depto',
            name='cobro_x_día',
        ),
    ]
