# Generated by Django 4.1.3 on 2022-12-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp1', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(max_length=30, verbose_name='Fecha de entrada')),
                ('date_out', models.DateField(max_length=30, verbose_name='Fecha de salida')),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Booking',
                'ordering': ['date_registered'],
            },
        ),
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_price', models.IntegerField(verbose_name='Precio diario')),
                ('manag_cost', models.IntegerField(verbose_name='Costo de gestion')),
                ('maint_cost', models.IntegerField(verbose_name='Costo de mantenimiento')),
                ('clean_cost', models.IntegerField(verbose_name='Costo de limpieza')),
                ('gain', models.IntegerField(verbose_name='Ganancia')),
                ('reserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpApp1.booking')),
            ],
            options={
                'verbose_name': 'Ganancia',
                'verbose_name_plural': 'Ganancias',
                'db_table': 'Gain',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('tel', models.CharField(max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'db_table': 'Person',
                'ordering': ['last_name'],
            },
        ),
        migrations.DeleteModel(
            name='Depto',
        ),
        migrations.DeleteModel(
            name='Ganancia',
        ),
        migrations.DeleteModel(
            name='Inquilino',
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpApp1.person', verbose_name='Inquilino'),
        ),
    ]
