# Generated by Django 4.1.3 on 2022-12-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp1', '0006_booking_gain_person_delete_depto_delete_ganancia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gain',
            old_name='reserv',
            new_name='booking',
        ),
    ]
